use jni::JNIEnv;
use jni::objects::JClass as jclass;
pub trait TestJNI {
    /* automatically generated by rust-bindgen */
    
    #[no_mangle]
    fn Java_Test_testInit(arg1: *mut JNIEnv, arg2: jclass);

    #[no_mangle]
    fn Java_Test_runTests(arg1: *mut JNIEnv, arg2: jclass);

    
}
