/// This file is generated by the build script of this crate, do not edit. Edit src/java/Test.java
/// to alter/generate native methods for the java native interface.

#[allow(non_snake_case)]
pub trait TestJNI {
    /* automatically generated by rust-bindgen */
    
    #[no_mangle]
    fn Java_Test_runTests(arg1: ::jni::JNIEnv, arg2: ::jni::objects::JClass) -> ::jni::sys::jstring;

    
}
