[package]
name = "botietests"
version = "0.1.0"
authors = ["gpace <greg.pace@bo.tie>"]
edition = "2018"

[dependencies]
bo-tie= { path="../../../" }
jni = "~0.10.2"

[build-dependencies]
bindgen= "~0.43.1"
